### ISSUE TITLE
Update GDAL installation 

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/vDistrict#2]
Fix the GDAL installation. 

Adapt the installation and readme, so the wheels by Gohlke are used. 

https://github.com/cgohlke/geospatial-wheels/

**Comment by c0nb4** [comment]
@nlongn22 can you update the GDAL installation, test and verify the installation. Additionally check for the option to install usesgraphs and djangoteaser.

**Comment by nlongn22** [comment]
Following the guide in README i encountered some issues. Below are the exact steps I followed with comments regarding an issue (or not).

### DB setup (Docker, 3DCityDB, InfluxDB, ADE)
1. run Docker with (was OK):
`docker run -dit --name citydb-container -p 5555:5432 -e "SRID=25832" -e "SRSNAME=urn:adv:crs:ETRS89_UTM32*DE_DHHN92_NH" -e "CITYDBNAME=citydb" -e "POSTGRES_USER=admin" -e "POSTGRES_PASSWORD=admin" tumgis/3dcitydb-postgis`
2. pull InfluxDB with (was OK):
`docker pull influxdb`
3. run Docker with (was OK):
`docker run --name=influxdb -d -p 8086:8086 -v /media/influxdb_backup/:/backup influxdb`
4. jump into the InfluxDB console for db and user creation (here was a problem):
```
  $ docker exec -it influxdb bash
  $ influx

  # CREATE DATABASE vdistrict
  # CREATE USER vdistrict WITH PASSWORD 'vdistrict' WITH ALL PRIVILEGES
```
This assumes InfluxDB version v1.x but the version Docker pulls is 2.x which doesn't support these command line commands. Instead I needed to use the GUI version accessible by going to `http://localhost:8086`. This was also the easiest way IMO. There we are presented a user creation screen which you need to fill out. After that a personal token is showed which needs to be saved. After user creation the README guide says we need to create a database called `vdistrict` (btw InfluxDB often refers to a 'database' as 'bucket'). The database can either be created using the GUI or we can use this command in the command line instead (we are still inside our Docker container btw!):
1.1. authenticate the CLI with our personal token (showed after user creation):
`export INFLUX_TOKEN=<<your-token>>`
1.2. create the bucket (database) via CLI:
`influx bucket create -n vdistrict --org <<your-org-name>>`

**Comment by nlongn22** [comment]
> Fix the GDAL installation.
> 
> Adapt the installation and readme, so the wheels by Gohlke are used.
> 
> https://github.com/cgohlke/geospatial-wheels/

The provided repo doesn't show any Linux installation steps (only Windows). But per discussion via Webex here is a link to a Debian distribution:
https://tracker.debian.org/pkg/gdal

**Comment by c0nb4** [comment]
Thanks, 

so from your text I understand that there are a few dependencies errors that we need to update. 

1. influxdb 
2. Most likely conda and python to newer versions (?)

I'll update the paths of the installation. Have you tried with the versions hosted on github? e.g. https://github.com/TUB-DVG/djangoCityDB
